spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/abb_tech
      username: psg_user
      password: pass

  jpa:
    hibernate:
      ddl-auto: create